version: '2'
services:

  jenkins_master:
    image: 'ferhimedamine/jenkins'
    container_name: "jenkins_master"
    privileged: true
    environment:
      - "DOCKER_API_VERSION=1.23"
    ports:
      - 8080:8080
    volumes:
      - ./job-config/generator.yml:/opt/jenkins-job/generator.yml
      - ./job-config/jobx.yml:/opt/jenkins-job/jobx.yml
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
